services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake test && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
